import { Prisma } from '@prisma/client';

export interface OrderFormData {
  serviceId: string;
  variantId: string;
  customerName: string;
  customerPhone: string;
  additionalPhone?: string | null;
  customerEmail?: string | null;
  address?: string | null;
  governorate?: string | null;
  city?: string | null;
  district?: string | null;
  street?: string | null;
  buildingNumber?: string | null;
  apartmentNumber?: string | null;
  landmark?: string | null;
  notes?: string | null;
  adminNotes?: string | null;
  deliveryType?: 'OFFICE' | 'DELIVERY';
  deliveryFee?: number;
  discount?: number;
  totalCents: number;
  birthDate?: string | null;
  fatherName?: string | null;
  idNumber?: string | null;
  motherName?: string | null;
  nationality?: string | null;
  gender?: 'male' | 'female' | null;
  wifeName?: string | null;
  wifeMotherName?: string | null;
  paymentMethod?: string | null;
  paidAmount?: number;
  photographyLocation?: string | null;
  photographyDate?: string | null;
  quantity?: number;
  attachedDocuments?: string[] | null;
  hasAttachments?: boolean;
  originalDocuments?: string | null;
  selectedFines?: Record<string, unknown>[] | null;
  finesDetails?: Record<string, unknown> | null;
  servicesDetails?: Record<string, unknown> | null;
  policeStation?: string | null;
  pickupLocation?: string | null;
  customerFollowUp?: string | null;
  marriageDate?: string | null;
  divorceDate?: string | null;
  deathDate?: string | null;
  deceasedName?: string | null;
  destination?: string | null;
  title?: string | null;
  formSerialNumber?: string | null;
  promoCode?: string | null;
  manualServices?: Array<{ serviceId: string; quantity: number; price: number }>;
  uploadedDocuments?: Array<{
    originalName: string;
    filename: string;
    filePath: string;
    fileType: string;
    fileSize: number;
  }>;
}

export interface FormSerialWithDetails {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  orderId?: string | null;
  formTypeId: string;
  serialNumber: string;
  consumed?: boolean;
  consumedAt?: Date | null;
  addedByAdminId?: string | null;
  consumedByAdminId?: string | null;
}

export interface OrderResponse {
  id: string;
  service: { name: string; slug: string };
  variant: { name: string; priceCents: number; etaDays: number };
  createdByAdmin: { id: string; name: string; email: string };
  user: { id: string; name: string; email: string; phone: string };
  payment?: { id: string; amount: number; method: string; status: string; senderPhone?: string };
  _count: { orderDocuments: number };
  status: string;
  customerName: string;
  customerPhone: string;
  additionalPhone: string | null;
  customerEmail: string | null;
  address: string;
  governorate: string;
  city: string;
  district: string;
  street: string;
  buildingNumber: string;
  apartmentNumber: string;
  landmark: string;
  notes: string;
  adminNotes: string;
  deliveryType: string;
  deliveryFee: number;
  otherFees: number;
  discount: number;
  discountAmount: number;
  promoCodeId: string | null;
  totalCents: number;
  totalPrice: number;
  createdAt: Date;
  updatedAt: Date;
  birthDate: Date | null;
  fatherName: string;
  idNumber: string;
  motherName: string;
  nationality: string;
  gender: string | null;
  wifeName: string | null;
  wifeMotherName: string | null;
  photographyLocation: string;
  photographyDate: Date | null;
  customerFollowUp: string;
  policeStation: string;
  pickupLocation: string;
  attachedDocuments: string | null;
  hasAttachments: boolean;
  originalDocuments: string;
  quantity: number;
  selectedFines: string | null;
  finesDetails: string | null;
  servicesDetails: string | null;
  serviceDetails: string;
  marriageDate: Date | null;
  divorceDate: Date | null;
  deathDate: Date | null;
  deceasedName: string;
  destination: string | null;
  title: string | null;
  workOrderNumber: string | null;
  paidAmount: number;
  remainingAmount: number;
}
